site_name: Curso de programación de NFMS4REDD
theme: 'material'
markdown_extensions: [codehilite]
pages:
- Home: index.md
- Cliente:
    - 'Hola mundo': client/hello_world.md
    - 'Añadir elementos a la interfaz': client/add_ui.md
    - 'Manejar eventos': client/events.md
    - 'Añadir funcionalidad al mapa': client/add_map_functionality.md
- Servidor:
    - 'Hola mundo': server/hello_world.md
    - 'Servlet de configuración': server/config_servlet.md
    - 'Acceso a base de datos': server/db_servlet.md
- Empaquetado y publicación:
    - 'Empaquetar plugin cliente': deploy/client.md
    - 'Empaquetar plugin servidor': deploy/server.md
    - 'Crear una nueva aplicación': deploy/new_app.md
    - 'Licencias': deploy/licenses.md

