site_name: Curso de programación de NFMS4REDD
theme: 'material'
markdown_extensions: [codehilite]
pages:
- Índice: index.md
- Preparación: setup.md
- Cliente:
    - 'Hola mundo': client/hello_world.md
    - 'Añadir elementos a la interfaz': client/add_ui.md
    - 'Reutilizar funcionalidad': client/reuse.md
    - 'Manejar eventos': client/events.md
    - 'Añadir funcionalidad al mapa': client/add_map_functionality.md
- Servidor:
    - 'Hola mundo': server/hello_world.md
    - 'Servlet de configuración': server/config_servlet.md
    - 'Servlet de acceso a base de datos': server/db_servlet.md
    - 'Consideraciones sobre el despliegue': server/deploy_considerations.md
- Ejercicios: exercises.md
